### ISSUE TITLE
(python) 변수 type 에 대한 몇 가지 오류

### ISSUE THREAD

**Issue by catahat** [SpiralMoon/maplestory.openapi#40]
1.
https://github.com/SpiralMoon/maplestory.openapi/blob/700a5eb62d660cbe70076aa6cc8eac3a7f03bd35/python/maplestory_openapi/api/dto/character/character_item_equipment.py#L309

CharacterItemEquipment.title can be null ("title": null)

`title: CharacterItemEquipmentTitle |  None
`
2.
https://github.com/SpiralMoon/maplestory.openapi/blob/700a5eb62d660cbe70076aa6cc8eac3a7f03bd35/python/maplestory_openapi/api/dto/character/character_basic.py#L26

CharacterBasic.character_guild_name can be null ("character_guild_name": null)
`character_guild_name: str | None
`
3.
https://github.com/SpiralMoon/maplestory.openapi/blob/700a5eb62d660cbe70076aa6cc8eac3a7f03bd35/python/maplestory_openapi/api/dto/character/character_item_equipment.py#L291

CharacterItemEquipmentTitle.date_option_expire can be "expired" ("date_option_expire": "expired")
`date_option_expire: datetime | None | str
`

**Comment by SpiralMoon** [comment]
solved https://github.com/SpiralMoon/maplestory.openapi/pull/41, https://github.com/SpiralMoon/maplestory.openapi/pull/42

**Comment by SpiralMoon** [comment]
released v2.3.2
